### ISSUE TITLE
Vivado - critical warning

### ISSUE THREAD

**Issue by remydemy** [open-sdr/openwifi-hw#101]
Hei,

My endgoal is to make the [Radar for openwifi](https://github.com/open-sdr/openwifi/blob/06fbd98167853a5d46c801bea395cf55440140ae/doc/app_notes/radar-self-csi.md) work on my antsdr E310. For this I'm currently doing the following steps (since I first need to create the appropriate files in the sdk folder):

```
./prepare_adi_lib.sh $XILINX_DIR
./prepare_adi_board_ip.sh $XILINX_DIR $BOARD_NAME
./get_ip_openofdm_rx.sh
cd openwifi-hw/boards/$BOARD_NAME/
../create_ip_repo.sh $XILINX_DIR
source ./openwifi.tcl
Click "Generate Bitstream" in the Vivado GUI.
```

At the end of the bitstream generation I get the following warning:

![Screenshot from 2023-12-22 11-45-43](https://github.com/open-sdr/openwifi-hw/assets/64281069/efe52ee6-aa71-4cd4-b679-beea4250d179)

Is this an important issue? Because I can still export the bitstream, however my FPGA is later on stuck while executing `./wgd.sh drv_and_fpga.tar.gz`. And I don't understand what the issue could be.

Best regards,
Emily

**Comment by JiaoXianjun** [comment]
This is by design.
