### ISSUE TITLE
焦博士你好，我想问一下关于openofdm_tx模块的dot11_tx.v中，关于BCC模块的reset机制问题。

### ISSUE THREAD

**Issue by wjq110** [open-sdr/openwifi-hw#105]
`assign enc_reset = phy_tx_arest | state1 == S1_WAIT_PKT | plcp_bit_cnt == 23 | plcp_bit_cnt == 47;`
您原来的代码中，会在SIG字段的第23bit和第47bit对BCC模块进行reset。当发送ht帧时，这个机制会导致在SIG字段中重置BCC模块，与接收机的解码机制是不是有一定区别。接收机中好像时直接把所有数据直接一起解码的，不会区分不同symbol。

**Comment by ll550** [comment]
I guess because the encoded bits sequence in the rx side appended  the tail bits for each field that will revert the decoder back to the initial state.  so the decoder can accept the complete sequence.
