### ISSUE TITLE
the synthesis (Run synthesis) stage fails.

### ISSUE THREAD

**Issue by chenmo234** [open-sdr/openwifi-hw#107]
![20240529142007](https://github.com/open-sdr/openwifi-hw/assets/131273707/b445d3de-8eda-409e-8b4c-1b5ca18bb196)
https://github.com/open-sdr/openwifi-hw/issues/59  My steps are exactly the same as his, and I have already added the Viterbi Decoder.

**Comment by AnVuNam** [comment]
Hi, I'm also having the same problem. Have you solved it yet?

**Comment by chenmo234** [comment]
> Hi, I'm also having the same problem. Have you solved it yet?

Yes, this is my contact information.    c2385405729
