### ISSUE TITLE
rom contents in legacy long preamble is periodic

### ISSUE THREAD

**Issue by ll550** [open-sdr/openwifi-hw#114]
Hi there, 

I just dived into the brilliant project openwifi, and tried to get used to it from a very fundamental place physcal layer. I found a quite interesting thing that the contents in the rom l_ltf_rom.v is periodic. I guess it could be simplified as in l_stf_rom.v.

l_ltf_rom l_ltf_rom (
    .addr(preamble_addr[5:0]), #addr(preamble_addr)
    .dout(l_ltf)
);

and remove the contents of addr beyond 64 in l_stf_rom.v 

I am not very familiar with the WiFi protocol, so It may not be right. If anyone can figure it out, please give me some comments.

**Comment by mmehari** [comment]
Indeed that is correct. 
As you can see in the OFDM packet structure (https://openofdm.readthedocs.io/en/latest/sync_long.html#fig-training)
the long preamble duration is 8 μs (160 samples), and contains two identical long training sequence (LTS), 64 samples each and a cyclic prefix of 32 samples.
