### ISSUE TITLE
Data format of IQ 

### ISSUE THREAD

**Issue by hyanki** [open-sdr/openwifi-hw#18]
Hi
I want to know that what is data format of IQ in 16 bit in receive  side?
In demodulater.v why scaling is taken 1024 though input is in 16 bit?
Regards
J S Hyanki

**Comment by JiaoXianjun** [comment]
You can read document of openofdm: https://openofdm.readthedocs.io/en/latest/

**Comment by hyanki** [comment]
Hi jiao
Basically in demodulate.v , input is 16 bit
but for demaping max value is taken 1024 which is 10 bit. Why?
Regards
J S Hyanki

**Comment by JiaoXianjun** [comment]
because the signal is scaled to that range by the processing steps.

**Comment by hyanki** [comment]
You mean output of FFT block.

**Comment by JiaoXianjun** [comment]
Could be. And also equalization.

**Comment by hyanki** [comment]
So maximum value coming from fft block is 1024.

**Comment by JiaoXianjun** [comment]
from euqalization module. Fft output is not fed to demodulate module directly. There is a equalisation module before the demodulation. 

1024 is just a reference amplitude to decide the  decision threshold inside demodulation.

**Comment by hyanki** [comment]
Ok.
I want to know that how much doppler can cope this ref design?

**Comment by JiaoXianjun** [comment]
We never test this. I think it should be like several 10KHz.

**Comment by hyanki** [comment]
Ok
Thanks for your support.
Regards

**Comment by JiaoXianjun** [comment]
Hello,

Would you please tell us your email? If you could also introduce yourself bit (student? Company? University?), that would be perfect. We might send out some questions to listen for user feed feedback.

Thanks.

**Comment by hyanki** [comment]
Hi
My mail id is hyankijitu@gmail.com
Regards
J S Hyanki

**Comment by JiaoXianjun** [comment]
Thanks!
