### ISSUE TITLE
system module

### ISSUE THREAD

**Issue by fatihilig-fpga** [open-sdr/openwifi-hw#26]
First of all thank you for your help.
I couldn't find the system.v sub-module which is attached into dropbox link shown below. 
https://www.dropbox.com/s/wmvgghgtb90bjm4/issuePic.png?dl=0

[https://github.com/open-sdr/openwifi-hw/blob/master/boards/adrv9361z7035/src/system_wrapper.v](url)
Have a great day.

**Comment by JiaoXianjun** [comment]
Hello,

Yes we can help. But firstly would you please send me (xianjun.jiao@ugent.be) information about you? Student? (MS? PhD?), or employee of which company? Thanks!

**Comment by suokea** [comment]
您好，请问您有没有关于xilinx SDK的代码，麻烦能不能让我参考一下

**Comment by suokea** [comment]
Hello!
Do you have any Xilinx SDK code for me to refer to? Thank you very much

**Comment by JiaoXianjun** [comment]
> Hello!
> Do you have any Xilinx SDK code for me to refer to? Thank you very much

Hello,

Yes we can help. But firstly would you please send me (xianjun.jiao@ugent.be) information about you? Student? (MS? PhD?), or employee of which company? Thanks!

**Comment by JiaoXianjun** [comment]
The SDK files are in openwifi-hw/boards/zcu102_fmcs2/sdk/

Please Check the sdk_update.sh in README:

```
In Vivado:
Open Block Design
Tools --> Report --> Report IP Status
Generate Bitstream
(Will take a while)
File --> Export --> Export Hardware... --> Include bitstream --> OK
File --> Launch SDK --> OK, then close SDK
In Linux:
cd openwifi-hw/boards
./sdk_update.sh board_name
git commit -a -m "new fpga img for openwifi (or comments you want to make)"
git push
(Above make sure you can pull this new FPGA from openwifi submodule directory: openwifi-hw)
```

**Comment by suokea** [comment]
Hello!
Sorry to disturb you again. I found the openwifi HW code on GitHub. After downloading it into a zip file, what's the reason for the decompression failure?

（您好！
抱歉，再次打扰。我在GITHUB上找到了openwifi-hw的代码，下载成ZIP文件后，解压失败是什么什么原因呢？）






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-sdr/openwifi-hw"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月29日(星期五) 晚上6:45
收件人:&nbsp;"open-sdr/openwifi-hw"<openwifi-hw@noreply.github.com&gt;;
抄送:&nbsp;"即使不确定"<821252745@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [open-sdr/openwifi-hw] system module (#26)





 
The SDK files are in openwifi-hw/boards/zcu102_fmcs2/sdk/
 
Please Check the sdk_update.sh in README:
 In Vivado: Open Block Design Tools --&gt; Report --&gt; Report IP Status Generate Bitstream (Will take a while) File --&gt; Export --&gt; Export Hardware... --&gt; Include bitstream --&gt; OK File --&gt; Launch SDK --&gt; OK, then close SDK In Linux: cd openwifi-hw/boards ./sdk_update.sh board_name git commit -a -m "new fpga img for openwifi (or comments you want to make)" git push (Above make sure you can pull this new FPGA from openwifi submodule directory: openwifi-hw)

**Comment by JiaoXianjun** [comment]
The zip file is not created by us. It is created by github when we publish a release.
I suggest you download again. Or use git clone command.
