### ISSUE TITLE
run openwifi.tcl

### ISSUE THREAD

**Issue by 18845725896peng** [open-sdr/openwifi-hw#32]
hello,
  when I run openwifi.tcl,
cd /home/zhangpeng/desktop/openwifi-hw-master/boards/zc706_fmcs2
source ./openwifi.tcl
# set  fd  [open  "openwifi_rev.coe"  w]
fatal: 不是 git 仓库（或者直至挂载点 / 的任何父目录）
停止在文件系统边界（未设置 GIT_DISCOVERY_ACROSS_FILESYSTEM）。
    while executing
"exec git log -1 --pretty=%h"
    invoked from within
"set HASHCODE [exec git log -1 --pretty=%h]"
    (file "./openwifi.tcl" line 23)

Is this a Git problem? I am not familiar with git

Looking forward your reply

**Comment by 18845725896peng** [comment]
it worked

**Comment by MehmettAkiff** [comment]
how can you solve this problem ?
