### ISSUE TITLE
802.11af Implementation for TVWS

### ISSUE THREAD

**Issue by eshikafe** [open-sdr/openwifi-hw#38]
Please is it possible to extend openwifi to support 802.11af on any FPGA SoC? If yes, how much effort will be required?

802.11af defines enhancements to the 802.11 WLAN physical layer (PHY) and medium access control (MAC) specifications to support operation in the TV white space (TVWS) spectrum in the VHF and UHF bands between 54 and 790 MHz.

Thanks

**Comment by JiaoXianjun** [comment]
Sorry we don’t know how big the difference between 11af and 11agn, hard to say.
