### ISSUE TITLE
dma_data of tx_intf not connected

### ISSUE THREAD

**Issue by catkira** [open-sdr/openwifi-hw#57]
I managed to synthesize everything with vivado 2022.1. The only thing that looks strange is, that the following inputs of tx_intf are unconnected:

dma_data
dma_valid

Is that correct or a problem with my vivado 2022.1?

**Comment by JiaoXianjun** [comment]
That is known unused port by purpose. No problem.

**Comment by catkira** [comment]
ok thanks!
