### ISSUE TITLE
May I ask which licenses Vivado needs besides Xilinx Viterbi Decoder license, because the Bitstream and HDF files we often compile cannot be used, thank you

### ISSUE THREAD

**Issue by zhuzhineng** [open-sdr/openwifi-hw#62]
May I ask which licenses Vivado needs besides Xilinx Viterbi Decoder license, because the Bitstream and HDF files we often compile cannot be used, thank you

**Comment by chenmo234** [comment]
I am also using E310 to deploy openwifi. Can I ask you some questions? Here is my contact information: c2385405729.
