### ISSUE TITLE
How to expand the data bit width of Side_Info from 64bit to 128bit?

### ISSUE THREAD

**Issue by KrisYuFi** [open-sdr/openwifi-hw#68]
Hello, Dr. Jiao.
We are using your image.
**My modification**
    I saw that the top file for **side_ch** had a predefined data bit width and thought I could modify it directly. So, I tried modifying the **side_ch** IP Core of the FPGA , I want to use it to get more information at the same time, because I want to add some functionality, I tried to change the bit width of the data from side_ch to PS using DMA directly from 64bit to 128bit, and the width of the device tree to 128bit, but when using Linux script:`./side_ch_ctl g`.The **side_info_count** does not increase, which means no data send to PS.
![image](https://user-images.githubusercontent.com/49112137/189522443-3d8ed1d4-7121-4ab7-8a45-0c078560451c.png)
![image](https://user-images.githubusercontent.com/49112137/189523625-82ffe5c9-5462-4c12-8c3c-6de9c1eedb9d.png)
![image](https://user-images.githubusercontent.com/49112137/189522485-7ace9fa2-610e-4c0b-b58b-35d1a67b7695.png)
![image](https://user-images.githubusercontent.com/49112137/189522518-0c94e4fc-1c53-4bf4-8f68-fc0316efe4f2.png)

**Our Board/hardware type:**
     Based on fcms2+zedboard.

**My debug efforts:**
      After a lot fruitless attempts, I looked at some of the signals using ILA and found that the AXI, which might be used to control the SIDE_CH cycle for data acquisition, might not be working properly.
![image](https://user-images.githubusercontent.com/49112137/189523035-2ab4e611-8992-4c1d-bfc6-ef0552cbe873.png)
The above is the online Debug diagram of my modified FPGA project.
![image](https://user-images.githubusercontent.com/49112137/189523176-e6272af9-629d-4697-9750-287255d62418.png)
The above is yours.
        The key is that the signal line slv_reg_wren, which should appear periodically.After the modification, it only becomes high the first time I execute `insmod side_ch.ko` and`./side_ch_ctrl g.`
**I guess**:Perhaps AXI is not working properly because DMA is passing 128 bits at a time but only 64bit is coming out?
Could you give me some suggestions about changing the data bit width?

**Comment by JiaoXianjun** [comment]
First of all, check your ARM CPU spec of your board, to confirm it support 128bit DMA or not.

Instead of extend 64 to 128, you should consider change the RAM and state machine inside side_ch (and python script on computer) to put more 64bits into single DMA transaction (more 64bit words per transaction).

**Comment by KrisYuFi** [comment]
> First of all, check your ARM CPU spec of your board, to confirm it support 128bit DMA or not.
> 
> Instead of extend 64 to 128, you should consider change the RAM and state machine inside side_ch (and python script on computer) to put more 64bits into single DMA transaction (more 64bit words per transaction).

Thank you. I'll give it a try. I've definitely got more 64bit data.
