### ISSUE TITLE
porting open-wifi to ad9375

### ISSUE THREAD

**Issue by andrew712** [open-sdr/openwifi-hw#73]
Hello, I want to try to port the project from zc706 - ad9361 to zc706 - adrv9375, can you give advice on how to do it correctly and what difficulties it can be, as I understand one of the problems is setting up ad9375 itself, as I see the source hdl for ad9375 is very different, is jesd204b used?
  vivado 2018.3, zc706-adrv9375, adi linux 2019R1

**Comment by JiaoXianjun** [comment]
https://github.com/open-sdr/openwifi#porting-guide
