### ISSUE TITLE
rssi issue

### ISSUE THREAD

**Issue by guessaname** [open-sdr/openwifi-hw#84]
Dear Xianjun,

I have a question about rssi calculation in module xpu. The average of IQ absolute value is used instead of IQ energy which usually denoted as the square of IQ. Is there any special assumption on this?

Thanks,
Lei

**Comment by JiaoXianjun** [comment]
Just to save some FPGA resources. The result is still correct, because we use a lookup table to guarantee this.

**Comment by guessaname** [comment]
Thanks for your reply. I will do more research on it.
